version: '3.6'
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
      - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./certs-data}:/data/letsencrypt
    depends_on:
      - wordpress
    restart: always

  webp-server:
    image: webpsh/webps:latest
    restart: always
    container_name: webp-server
    volumes:
      - ./webp-server/config.json:/etc/config.json
      - ./wordpress:/var/www/html
    ports:
      - 3333:3333
